{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 3,
  "build_id": "v0.98.2",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "BOOMING_CONCH",
                "title": {
                  "key": "BOOMING_CONCH.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "LOST_COFFER",
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 99,
            "current_hp": 64,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BOOMING_CONCH.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.BOOMING_CONCH",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "LAVA_ROCK",
                "title": {
                  "key": "LAVA_ROCK.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "NEOWS_TORMENT",
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_NECROBINDER"
              }
            ],
            "current_gold": 99,
            "current_hp": 39,
            "damage_taken": 13,
            "event_choices": [
              {
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 52,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.PRECARIOUS_SHEARS",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "LOST_COFFER",
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "NEOWS_TORMENT",
                "title": {
                  "key": "NEOWS_TORMENT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CURSED_PEARL",
                "title": {
                  "key": "CURSED_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.KINGLY_KICK"
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LOST_COFFER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RUPTURE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.TRUE_GRIT"
              }
            ],
            "current_gold": 110,
            "current_hp": 69,
            "damage_taken": 1,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.ASHWATER",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.VEILPIERCER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAVEBLAST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.SCULPTING_STRIKE"
              }
            ],
            "current_gold": 114,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BULWARK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.KNOW_THY_PLACE"
              }
            ],
            "current_gold": 109,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.FORGOTTEN_RITUAL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.JUGGLING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 3,
                "id": "CARD.FORGOTTEN_RITUAL"
              }
            ],
            "current_gold": 121,
            "current_hp": 73,
            "damage_taken": 2,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEATHS_DOOR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 125,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.GLOW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HEGEMONY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PARRY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GLOW"
              }
            ],
            "current_gold": 121,
            "current_hp": 59,
            "damage_taken": 1,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 121,
            "current_hp": 73,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          },
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 125,
            "current_hp": 39,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 121,
            "current_hp": 59,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LEGENDS_WERE_TRUE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.BATTLE_TRANCE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.SHRUG_IT_OFF"
              },
              {
                "floor_added_to_deck": 5,
                "id": "CARD.BATTLE_TRANCE"
              }
            ],
            "current_gold": 24,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 97,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.BORROWED_TIME"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.BORROWED_TIME"
              }
            ],
            "current_gold": 53,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 72,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUARDS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.VOLLEY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ROLLING_BOULDER"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 46,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TUNING_FORK",
                "was_picked": false
              },
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": false
              },
              {
                "choice": "RELIC.DINGY_RUG",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.FEEL_NO_PAIN"
              }
            ],
            "current_gold": 39,
            "current_hp": 78,
            "damage_taken": 1,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.CAPTURE_SPIRIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BONE_SHARDS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.CAPTURE_SPIRIT"
              }
            ],
            "current_gold": 60,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.BONE_BREW",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CONQUEROR"
              }
            ],
            "current_gold": 56,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 39,
            "current_hp": 78,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.TRUE_GRIT"
            ]
          },
          {
            "current_gold": 60,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.CAPTURE_SPIRIT"
            ]
          },
          {
            "current_gold": 56,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.KINGLY_KICK"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 8,
                "id": "CARD.EVIL_EYE"
              }
            ],
            "current_gold": 65,
            "current_hp": 50,
            "damage_taken": 34,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_used": [
              "POTION.LIQUID_BRONZE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.REPTILE_TRINKET",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.LEGION_OF_BONE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LETHALITY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GRAVEBLAST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 8,
                "id": "CARD.LEGION_OF_BONE"
              }
            ],
            "current_gold": 88,
            "current_hp": 17,
            "damage_taken": 22,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BONE_BREW"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SHOVEL",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.GAMMA_BLAST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFLECT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GAMMA_BLAST"
              }
            ],
            "current_gold": 82,
            "current_hp": 3,
            "damage_taken": 56,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_used": [
              "POTION.SKILL_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 101,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 122,
            "current_hp": 17,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 119,
            "current_hp": 3,
            "damage_taken": 0,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.CANDELABRA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 101,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.FORGOTTEN_RITUAL"
            ]
          },
          {
            "current_gold": 122,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 119,
            "current_hp": 25,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PACTS_END"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.MOLTEN_FIST"
              }
            ],
            "current_gold": 133,
            "current_hp": 51,
            "damage_taken": 5,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MEAL_TICKET",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.DEBILITATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAPER_FORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLEANSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.DEBILITATE"
              }
            ],
            "current_gold": 153,
            "current_hp": 29,
            "damage_taken": 7,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.CRASH_LANDING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CRASH_LANDING"
              }
            ],
            "current_gold": 147,
            "current_hp": 6,
            "damage_taken": 19,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.MOLTEN_FIST"
              }
            ],
            "current_gold": 133,
            "current_hp": 51,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.SCULPTING_STRIKE"
              }
            ],
            "current_gold": 153,
            "current_hp": 22,
            "damage_taken": 7,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.HOLD_ON_0.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.HOLD_ON_0.options.HOLD_ON_1.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_REGENT"
              }
            ],
            "current_gold": 147,
            "current_hp": 3,
            "damage_taken": 3,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.HOLD_ON_0.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "防御"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 4,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              },
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "防御"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 4,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SLIPPERY_BRIDGE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.POMMEL_STRIKE"
              }
            ],
            "current_gold": 146,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.FRIENDSHIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.FRIENDSHIP"
              }
            ],
            "current_gold": 164,
            "current_hp": 22,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MANIFEST_AUTHORITY"
                },
                "was_picked": false
              }
            ],
            "current_gold": 160,
            "current_hp": 3,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_NORMAL",
            "monster_ids": [
              "MONSTER.CALCIFIED_CULTIST",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFLAME"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.POMMEL_STRIKE"
              }
            ],
            "current_gold": 156,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REAVE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 174,
            "current_hp": 22,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.DECISIONS_DECISIONS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DECISIONS_DECISIONS"
              }
            ],
            "current_gold": 168,
            "current_hp": 3,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ENERGY_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEWER_CLAM_NORMAL",
            "monster_ids": [
              "MONSTER.SEWER_CLAM"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 156,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.POMMEL_STRIKE"
            ]
          },
          {
            "current_gold": 174,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 168,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 37,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.COLOSSUS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.AGGRESSION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CASCADE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.COLOSSUS"
              }
            ],
            "current_gold": 231,
            "current_hp": 49,
            "damage_taken": 20,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_used": [
              "POTION.WEAK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.MISERY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.REAPER_FORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEMESNE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.MISERY"
              }
            ],
            "current_gold": 249,
            "current_hp": 41,
            "damage_taken": 0,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.GUARDS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOREGONE_CONCLUSION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRASH_LANDING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GUARDS"
              }
            ],
            "current_gold": 243,
            "current_hp": 1,
            "damage_taken": 40,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.WATERFALL_GIANT_BOSS",
            "monster_ids": [
              "MONSTER.WATERFALL_GIANT"
            ],
            "room_type": "boss",
            "turns_taken": 10
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "STORYBOOK",
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_COMPASS",
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 231,
            "current_hp": 73,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.YUMMY_COOKIE",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.POMMEL_STRIKE",
              "CARD.BASH",
              "CARD.BATTLE_TRANCE",
              "CARD.EVIL_EYE"
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "VERY_HOT_COCOA",
                "title": {
                  "key": "VERY_HOT_COCOA.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "STORYBOOK",
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PUMPKIN_CANDLE",
                "title": {
                  "key": "PUMPKIN_CANDLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 249,
            "current_hp": 61,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "VERY_HOT_COCOA.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.VERY_HOT_COCOA",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_SOUP",
                "title": {
                  "key": "NUTRITIOUS_SOUP.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TOASTY_MITTENS",
                "title": {
                  "key": "TOASTY_MITTENS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_COMPASS",
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 243,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 59,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.GOLDEN_COMPASS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLOOD_WALL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BODY_SLAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLUDGEON"
                },
                "was_picked": false
              }
            ],
            "current_gold": 240,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.DEFY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLEANSE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.DEFY"
              }
            ],
            "current_gold": 261,
            "current_hp": 59,
            "damage_taken": 2,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.SHIP_IN_A_BOTTLE",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.FLEX_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 257,
            "current_hp": 48,
            "damage_taken": 12,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 19,
                  "id": "CARD.VICIOUS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.JUGGLING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 19,
                "id": "CARD.VICIOUS"
              }
            ],
            "current_gold": 240,
            "current_hp": 79,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_FUTURE_OF_POTIONS.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Rarity": {
                    "type": "String",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "罕见"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_discarded": [
              "POTION.ASHWATER"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 19,
                  "id": "CARD.SOUL_STORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.MISERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BANSHEES_CRY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 19,
                "id": "CARD.SOUL_STORM"
              }
            ],
            "current_gold": 261,
            "current_hp": 59,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_FUTURE_OF_POTIONS.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Rarity": {
                    "type": "String",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "稀有"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_discarded": [
              "POTION.SHIP_IN_A_BOTTLE"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 19,
                  "id": "CARD.CHARGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CONQUEROR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ROYAL_GAMBLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.CHARGE"
              }
            ],
            "current_gold": 257,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_FUTURE_OF_POTIONS.pages.INITIAL.options.POTION.title",
                  "table": "events"
                },
                "variables": {
                  "Rarity": {
                    "type": "String",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "罕见"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_discarded": [
              "POTION.POWDERED_DEMISE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_FUTURE_OF_POTIONS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 240,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SHRUG_IT_OFF"
            ]
          },
          {
            "current_gold": 261,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BORROWED_TIME"
            ]
          },
          {
            "current_gold": 257,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.GLOW"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOOD_WALL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 21,
                "id": "CARD.MOLTEN_FIST"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.FEEL_NO_PAIN"
              }
            ],
            "current_gold": 253,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.BORROWED_TIME"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.POKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 21,
                "id": "CARD.BORROWED_TIME"
              },
              {
                "floor_added_to_deck": 21,
                "id": "CARD.GRAVE_WARDEN"
              }
            ],
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 5,
                "id": "CARD.BORROWED_TIME"
              }
            ],
            "current_gold": 275,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.SPOILS_OF_BATTLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MAKE_IT_SO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.CONQUEROR"
              },
              {
                "current_upgrade_level": 1,
                "id": "CARD.SPOILS_OF_BATTLE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.CONQUEROR"
              }
            ],
            "current_gold": 266,
            "current_hp": 41,
            "damage_taken": 7,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 253,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "MEND"
            ]
          },
          {
            "current_gold": 275,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.GRAVE_WARDEN"
            ]
          },
          {
            "current_gold": 266,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 34,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.VENERATE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 253,
            "current_hp": 90,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "STONE_OF_ALL_TIME.pages.INITIAL.options.LIFT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 90,
            "max_hp_gained": 10,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_discarded": [
              "POTION.STRENGTH_POTION"
            ]
          },
          {
            "current_gold": 275,
            "current_hp": 69,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "STONE_OF_ALL_TIME.pages.INITIAL.options.LIFT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 76,
            "max_hp_gained": 10,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_discarded": [
              "POTION.EXPLOSIVE_AMPOULE"
            ]
          },
          {
            "current_gold": 266,
            "current_hp": 85,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "STONE_OF_ALL_TIME.pages.INITIAL.options.LIFT.title",
                  "table": "events"
                },
                "variables": {
                  "DrinkRandomPotion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "力量药水"
                  },
                  "DrinkMaxHpGain": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  },
                  "PushHpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 6,
                    "bool_value": false,
                    "string_value": null
                  },
                  "PushVigorousAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 8,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 85,
            "max_hp_gained": 10,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_discarded": [
              "POTION.STRENGTH_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.STONE_OF_ALL_TIME",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 4,
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "completed_quests": [
              "CARD.SPOILS_MAP"
            ],
            "current_gold": 890,
            "current_hp": 90,
            "damage_taken": 0,
            "gold_gained": 637,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.AMETHYST_AUBERGINE",
                "was_picked": true
              }
            ]
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 4,
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "completed_quests": [
              "CARD.SPOILS_MAP"
            ],
            "current_gold": 913,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 638,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.TUNING_FORK",
                "was_picked": true
              }
            ]
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 4,
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "completed_quests": [
              "CARD.SPOILS_MAP"
            ],
            "current_gold": 898,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 632,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.ORICHALCUM",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.SQUASH"
              }
            ],
            "current_gold": 890,
            "current_hp": 90,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BUGSLAYER.pages.INITIAL.options.SQUASH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          },
          {
            "cards_gained": [
              {
                "id": "CARD.SQUASH"
              }
            ],
            "current_gold": 913,
            "current_hp": 69,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BUGSLAYER.pages.INITIAL.options.SQUASH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "cards_gained": [
              {
                "id": "CARD.EXTERMINATE"
              }
            ],
            "current_gold": 898,
            "current_hp": 85,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BUGSLAYER.pages.INITIAL.options.EXTERMINATION.title",
                  "table": "events"
                },
                "variables": {
                  "Card1": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "杀灭"
                  },
                  "Card2": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "压扁"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BUGSLAYER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 925,
            "current_hp": 90,
            "damage_taken": 0,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 946,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 937,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 925,
            "current_hp": 76,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 946,
            "current_hp": 55,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 937,
            "current_hp": 71,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_IRONCLAD"
              }
            ],
            "current_gold": 798,
            "current_hp": 90,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 52,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 14,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 871,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "bought_potions": [
              "POTION.STAR_POTION"
            ],
            "bought_relics": [
              "RELIC.BAG_OF_PREPARATION",
              "RELIC.BRONZE_SCALES"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PRODUCTION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ROLLING_BOULDER"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 366,
            "current_hp": 71,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 571,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.STAR_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              },
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              },
              {
                "choice": "RELIC.BELT_BUCKLE",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 29,
                  "id": "CARD.DARK_EMBRACE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BLOOD_WALL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 29,
                "id": "CARD.DARK_EMBRACE"
              }
            ],
            "current_gold": 835,
            "current_hp": 89,
            "damage_taken": 8,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 91,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DRAIN_POWER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCOURGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NO_ESCAPE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 902,
            "current_hp": 48,
            "damage_taken": 8,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 77,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.MEAL_TICKET",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LARGESSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 399,
            "current_hp": 48,
            "damage_taken": 24,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 86,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ICE_CREAM",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 835,
            "current_hp": 89,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DARK_EMBRACE"
            ]
          },
          {
            "current_gold": 902,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 77,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": true
              }
            ],
            "rest_site_choices": [
              "DIG"
            ]
          },
          {
            "current_gold": 399,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DECISIONS_DECISIONS"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.DOMINATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PILLAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEMOKINESIS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.DOMINATE"
              }
            ],
            "current_gold": 876,
            "current_hp": 92,
            "damage_taken": 0,
            "gold_gained": 41,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 3,
            "max_hp": 92,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STONE_CRACKER",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.TRANSFIGURE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DRAIN_POWER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.TRANSFIGURE"
              }
            ],
            "current_gold": 933,
            "current_hp": 48,
            "damage_taken": 8,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 8,
            "max_hp": 85,
            "max_hp_gained": 8,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RESONANCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GATHER_LIGHT"
              }
            ],
            "current_gold": 431,
            "current_hp": 31,
            "damage_taken": 18,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 87,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RAZOR_TOOTH",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 876,
            "current_hp": 92,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 92,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SQUASH"
            ]
          },
          {
            "current_gold": 933,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.TRANSFIGURE"
            ]
          },
          {
            "current_gold": 431,
            "current_hp": 72,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 41,
            "max_hp": 87,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.BRAND"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLOSSUS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRICADE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 33,
                "id": "CARD.BRAND"
              }
            ],
            "current_gold": 961,
            "current_hp": 82,
            "damage_taken": 17,
            "gold_gained": 85,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 93,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.EIDOLON"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ERADICATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALL_OF_THE_VOID"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 33,
                "id": "CARD.EIDOLON"
              }
            ],
            "current_gold": 1008,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 86,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.THE_SMITH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOREGONE_CONCLUSION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAT_INTO_SHAPE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.THE_SMITH"
              }
            ],
            "current_gold": 506,
            "current_hp": 55,
            "damage_taken": 18,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 88,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.GIGANTIFICATION_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.VULNERABLE_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "MEAT_CLEAVER",
                "title": {
                  "key": "MEAT_CLEAVER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "IRON_CLUB",
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CLAWS",
                "title": {
                  "key": "CLAWS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 961,
            "current_hp": 90,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "MEAT_CLEAVER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 8,
            "max_hp": 93,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.MEAT_CLEAVER",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "CLAWS",
                "title": {
                  "key": "CLAWS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "WAR_HAMMER",
                "title": {
                  "key": "WAR_HAMMER.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 19,
                  "id": "CARD.SOUL_STORM"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 25,
                  "id": "CARD.SQUASH"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 11,
                  "id": "CARD.DEBILITATE"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              }
            ],
            "current_gold": 1008,
            "current_hp": 78,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 29,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.TRI_BOOMERANG",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SAI",
                "title": {
                  "key": "SAI.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "CROSSBOW",
                "title": {
                  "key": "CROSSBOW.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 25,
                  "id": "CARD.EXTERMINATE"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 11,
                  "id": "CARD.CRASH_LANDING"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.KINGLY_KICK"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              }
            ],
            "current_gold": 506,
            "current_hp": 81,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 26,
            "max_hp": 88,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.TRI_BOOMERANG",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HOWL_FROM_BEYOND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 982,
            "current_hp": 94,
            "damage_taken": 0,
            "gold_gained": 21,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 4,
            "max_hp": 94,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198980444751
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.AFTERLIFE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WISP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.POKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 1016,
            "current_hp": 78,
            "damage_taken": 1,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 87,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 35,
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULWARK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CHILD_OF_THE_STARS"
              }
            ],
            "current_gold": 521,
            "current_hp": 75,
            "damage_taken": 7,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 89,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ASHEN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ANGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DISMANTLE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 1000,
            "current_hp": 95,
            "damage_taken": 0,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 95,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.FRUIT_JUICE",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.ATTACK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PULL_AGGRO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SLEIGHT_OF_FLESH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEFILE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 1030,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 88,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SPEED_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 36,
                  "id": "CARD.GLOW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.GLOW"
              }
            ],
            "current_gold": 531,
            "current_hp": 76,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 90,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 37,
                  "id": "CARD.SECRET_TECHNIQUE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 37,
                "id": "CARD.SECRET_TECHNIQUE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_IRONCLAD"
              }
            ],
            "current_gold": 474,
            "current_hp": 95,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 426,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 95,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.DRAGON_FRUIT",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 37,
                  "id": "CARD.PURITY"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 37,
                "id": "CARD.PURITY"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 407,
            "current_hp": 88,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 523,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 9,
            "max_hp": 88,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.WAR_PAINT",
                "was_picked": true
              },
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.LEGION_OF_BONE",
              "CARD.PURITY"
            ]
          },
          {
            "bought_relics": [
              "RELIC.TOOLBOX"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DARK_SHACKLES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MASTER_OF_STRATEGY"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 197,
            "current_hp": 76,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 334,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": false
              },
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TOOLBOX",
                "was_picked": true
              },
              {
                "choice": "RELIC.GORGET",
                "was_picked": false
              },
              {
                "choice": "RELIC.BLOOD_VIAL",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.INFERNAL_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BATTLE_TRANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DISMANTLE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 496,
            "current_hp": 90,
            "damage_taken": 19,
            "gold_gained": 22,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 14,
            "max_hp": 103,
            "max_hp_gained": 8,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_used": [
              "POTION.FRUIT_JUICE"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 38,
                  "id": "CARD.CAPTURE_SPIRIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RATTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.AFTERLIFE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 38,
                "id": "CARD.CAPTURE_SPIRIT"
              }
            ],
            "current_gold": 419,
            "current_hp": 80,
            "damage_taken": 9,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 89,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_MEMORIES",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 38,
                  "id": "CARD.ORBIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ORBIT"
              }
            ],
            "current_gold": 211,
            "current_hp": 69,
            "damage_taken": 8,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 91,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_used": [
              "POTION.HEART_OF_IRON"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CONSTRUCT_MENAGERIE_NORMAL",
            "monster_ids": [
              "MONSTER.PUNCH_CONSTRUCT",
              "MONSTER.CUBEX_CONSTRUCT",
              "MONSTER.CUBEX_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_IRONCLAD"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_IRONCLAD"
              }
            ],
            "current_gold": 496,
            "current_hp": 99,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 9,
            "max_hp": 112,
            "max_hp_gained": 9,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "COOK"
            ]
          },
          {
            "current_gold": 419,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.CAPTURE_SPIRIT"
            ]
          },
          {
            "current_gold": 211,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ORBIT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 528,
            "current_hp": 100,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 113,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.PANTOGRAPH",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 453,
            "current_hp": 80,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 243,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 41,
                  "id": "CARD.DARK_EMBRACE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 41,
                "id": "CARD.DARK_EMBRACE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_IRONCLAD"
              }
            ],
            "current_gold": 30,
            "current_hp": 113,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 373,
            "gold_spent": 125,
            "gold_stolen": 0,
            "hp_healed": 13,
            "max_hp": 113,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.VAMBRACE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 41,
                  "id": "CARD.AUTOMATION"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 41,
                "id": "CARD.AUTOMATION"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_NECROBINDER"
              }
            ],
            "current_gold": 51,
            "current_hp": 89,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 277,
            "gold_spent": 125,
            "gold_stolen": 0,
            "hp_healed": 9,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.GAMMA_BLAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONVERGENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPECTRUM_SHIFT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SEEKER_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAT_DOWN"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 93,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 150,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              },
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": false
              },
              {
                "choice": "RELIC.REPTILE_TRINKET",
                "was_picked": false
              },
              {
                "choice": "RELIC.PUNCH_DAGGER",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.WHIRLWIND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              }
            ],
            "current_gold": 73,
            "current_hp": 116,
            "damage_taken": 6,
            "gold_gained": 43,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 9,
            "max_hp": 116,
            "max_hp_gained": 3,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "relic_choices": [
              {
                "choice": "RELIC.RAINBOW_RING",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SCULPTING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.INVOKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 84,
            "current_hp": 68,
            "damage_taken": 22,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 90,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 42,
                  "id": "CARD.DECISIONS_DECISIONS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DECISIONS_DECISIONS"
              }
            ],
            "current_gold": 122,
            "current_hp": 38,
            "damage_taken": 32,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 92,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
            "monster_ids": [
              "MONSTER.MECHA_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_IRONCLAD"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_IRONCLAD"
              }
            ],
            "current_gold": 73,
            "current_hp": 125,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 9,
            "max_hp": 125,
            "max_hp_gained": 9,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "COOK"
            ]
          },
          {
            "current_gold": 84,
            "current_hp": 68,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.EIDOLON"
            ]
          },
          {
            "current_gold": 122,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 92,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.THE_SMITH"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 44,
                  "id": "CARD.RAMPAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLOSSUS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 44,
                "id": "CARD.RAMPAGE"
              }
            ],
            "current_gold": 109,
            "current_hp": 128,
            "damage_taken": 2,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 128,
            "max_hp_gained": 3,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.TIMES_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAP"
                },
                "was_picked": false
              }
            ],
            "current_gold": 112,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 91,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.CENTENNIAL_PUZZLE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 44,
                  "id": "CARD.LARGESSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULWARK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.LARGESSE"
              }
            ],
            "current_gold": 152,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 93,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SOUL_NEXUS_ELITE",
            "monster_ids": [
              "MONSTER.SOUL_NEXUS"
            ],
            "room_type": "elite",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BLOOD_WALL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              }
            ],
            "current_gold": 133,
            "current_hp": 131,
            "damage_taken": 2,
            "gold_gained": 24,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 5,
            "max_hp": 131,
            "max_hp_gained": 3,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 45,
                  "id": "CARD.GRAVE_WARDEN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FLATTEN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 45,
                "id": "CARD.GRAVE_WARDEN"
              }
            ],
            "current_gold": 120,
            "current_hp": 51,
            "damage_taken": 19,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 92,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.HEGEMONY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ALIGNMENT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.STARDUST"
                },
                "was_picked": false
              }
            ],
            "current_gold": 160,
            "current_hp": 30,
            "damage_taken": 10,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 94,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FABRICATOR_NORMAL",
            "monster_ids": [
              "MONSTER.FABRICATOR"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_IRONCLAD"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_IRONCLAD"
              }
            ],
            "current_gold": 133,
            "current_hp": 140,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 9,
            "max_hp": 140,
            "max_hp_gained": 9,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "rest_site_choices": [
              "COOK"
            ]
          },
          {
            "current_gold": 120,
            "current_hp": 78,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "max_hp": 92,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 160,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 43,
            "max_hp": 94,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 133,
            "current_hp": 116,
            "damage_taken": 31,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 141,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198980444751,
            "potion_used": [
              "POTION.SKILL_POTION",
              "POTION.SKILL_POTION",
              "POTION.COLORLESS_POTION"
            ]
          },
          {
            "current_gold": 120,
            "current_hp": 66,
            "damage_taken": 13,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 93,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          },
          {
            "current_gold": 160,
            "current_hp": 52,
            "damage_taken": 22,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 95,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_used": [
              "POTION.STAR_POTION",
              "POTION.GIGANTIFICATION_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DOORMAKER_BOSS",
            "monster_ids": [
              "MONSTER.DOOR"
            ],
            "room_type": "boss",
            "turns_taken": 4
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.BASH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.TRUE_GRIT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.FORGOTTEN_RITUAL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.SHRUG_IT_OFF"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.BATTLE_TRANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 8,
          "id": "CARD.EVIL_EYE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 13,
          "id": "CARD.POMMEL_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 14,
          "id": "CARD.POMMEL_STRIKE"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.COLOSSUS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.VICIOUS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.MOLTEN_FIST"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 25,
          "id": "CARD.SQUASH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 29,
          "id": "CARD.DARK_EMBRACE"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.DOMINATE"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.BRAND"
        },
        {
          "floor_added_to_deck": 37,
          "id": "CARD.SECRET_TECHNIQUE"
        },
        {
          "floor_added_to_deck": 41,
          "id": "CARD.DARK_EMBRACE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 44,
          "id": "CARD.RAMPAGE"
        }
      ],
      "id": 76561198980444751,
      "max_potion_slot_count": 3,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BOOMING_CONCH"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.REPTILE_TRINKET"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.PERMAFROST"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.MEAL_TICKET"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.YUMMY_COOKIE"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.AMETHYST_AUBERGINE"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 27,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.STONE_CRACKER"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.MEAT_CLEAVER"
        },
        {
          "floor_added_to_deck": 37,
          "id": "RELIC.DRAGON_FRUIT"
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.PANTOGRAPH"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.VAMBRACE"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.RAINBOW_RING"
        },
        {
          "floor_added_to_deck": 44,
          "id": "RELIC.BRONZE_SCALES"
        }
      ]
    },
    {
      "character": "CHARACTER.NECROBINDER",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_NECROBINDER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BODYGUARD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.UNLEASH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 6,
          "id": "CARD.CAPTURE_SPIRIT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 8,
          "id": "CARD.LEGION_OF_BONE"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 11,
          "id": "CARD.DEBILITATE"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.FRIENDSHIP"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.MISERY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.DEFY"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 19,
          "id": "CARD.SOUL_STORM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.BORROWED_TIME"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.GRAVE_WARDEN"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 25,
          "id": "CARD.SQUASH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.TRANSFIGURE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.EIDOLON"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 37,
          "id": "CARD.PURITY"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 38,
          "id": "CARD.CAPTURE_SPIRIT"
        },
        {
          "floor_added_to_deck": 41,
          "id": "CARD.AUTOMATION"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 45,
          "id": "CARD.GRAVE_WARDEN"
        }
      ],
      "id": 76561198237752388,
      "max_potion_slot_count": 5,
      "potions": [
        {
          "id": "POTION.DUPLICATOR",
          "slot_index": 0
        },
        {
          "id": "POTION.ENERGY_POTION",
          "slot_index": 1
        },
        {
          "id": "POTION.FLEX_POTION",
          "slot_index": 2
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BOUND_PHYLACTERY"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.PRECARIOUS_SHEARS"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.SHOVEL"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.HORN_CLEAT"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.VERY_HOT_COCOA"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.TUNING_FORK",
          "props": {
            "ints": [
              {
                "name": "SkillsPlayed",
                "value": 0
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.FESTIVE_POPPER"
        },
        {
          "floor_added_to_deck": 27,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.MEAL_TICKET"
        },
        {
          "floor_added_to_deck": 30,
          "id": "RELIC.STRIKE_DUMMY"
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.STRAWBERRY"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.TRI_BOOMERANG"
        },
        {
          "floor_added_to_deck": 37,
          "id": "RELIC.WAR_PAINT"
        },
        {
          "floor_added_to_deck": 37,
          "id": "RELIC.HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 2
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.POTION_BELT"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.GORGET"
        },
        {
          "floor_added_to_deck": 44,
          "id": "RELIC.CENTENNIAL_PUZZLE"
        }
      ]
    },
    {
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.KINGLY_KICK"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.KNOW_THY_PLACE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.GLOW"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.GAMMA_BLAST"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 11,
          "id": "CARD.CRASH_LANDING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 14,
          "id": "CARD.DECISIONS_DECISIONS"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.GUARDS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.CHARGE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.CONQUEROR"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.SPOILS_OF_BATTLE"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 25,
          "id": "CARD.EXTERMINATE"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.GATHER_LIGHT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 33,
          "id": "CARD.THE_SMITH"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.CHILD_OF_THE_STARS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 36,
          "id": "CARD.GLOW"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 38,
          "id": "CARD.ORBIT"
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.DECISIONS_DECISIONS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 44,
          "id": "CARD.LARGESSE"
        }
      ],
      "id": 76561199466895123,
      "max_potion_slot_count": 3,
      "potions": [
        {
          "id": "POTION.EXPLOSIVE_AMPOULE",
          "slot_index": 2
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LOST_COFFER"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.PENDULUM"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.CANDELABRA"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.REGAL_PILLOW"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.GOLDEN_COMPASS",
          "props": {
            "ints": [
              {
                "name": "GoldenPathAct",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.ORICHALCUM"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 27,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 29,
          "id": "RELIC.ICE_CREAM"
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.RAZOR_TOOTH"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.TRI_BOOMERANG"
        },
        {
          "floor_added_to_deck": 37,
          "id": "RELIC.TOOLBOX"
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 42,
          "id": "RELIC.RED_MASK"
        },
        {
          "floor_added_to_deck": 44,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        }
      ]
    }
  ],
  "run_time": 5288,
  "schema_version": 8,
  "seed": "QDRL84478S",
  "start_time": 1772935499,
  "was_abandoned": false,
  "win": true
}