{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 6,
  "build_id": "v0.99.1",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "MASSIVE_SCROLL",
                "title": {
                  "key": "MASSIVE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FOREGONE_CONCLUSION"
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "LOST_COFFER",
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "MASSIVE_SCROLL",
                "title": {
                  "key": "MASSIVE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "LARGE_CAPSULE",
                "title": {
                  "key": "LARGE_CAPSULE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.LIFT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TAG_TEAM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ENERGY_SURGE"
              }
            ],
            "current_gold": 99,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "MASSIVE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 60,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.MASSIVE_SCROLL",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SCROLL_BOXES",
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ADRENALINE"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.BEGONE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.BEGONE"
              }
            ],
            "current_gold": 107,
            "current_hp": 59,
            "damage_taken": 1,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.FIGHT_THROUGH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FIGHT_THROUGH"
              }
            ],
            "current_gold": 113,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.DAGGER_THROW"
              }
            ],
            "current_gold": 108,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.GLOW"
              },
              {
                "id": "CARD.SPOILS_OF_BATTLE"
              }
            ],
            "current_gold": 107,
            "current_hp": 59,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.GORGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "current_gold": 113,
            "current_hp": 46,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ]
          },
          {
            "cards_gained": [
              {
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "id": "CARD.ACROBATICS"
              }
            ],
            "current_gold": 108,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.GORGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 107,
            "current_hp": 69,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.INITIAL.options.ABSTAIN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "current_gold": 113,
            "current_hp": 36,
            "damage_taken": 18,
            "event_choices": [
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.INITIAL.options.IMMERSE.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.LINGER.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.LINGER.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.LINGER.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.EXIT_BATHS.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 8,
            "max_hp": 83,
            "max_hp_gained": 8,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          },
          {
            "current_gold": 108,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.INITIAL.options.ABSTAIN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ABYSSAL_BATHS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.RADIATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PILLAR_OF_CREATION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 120,
            "current_hp": 68,
            "damage_taken": 1,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_MEMORIES",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BEAM_CELL"
              }
            ],
            "current_gold": 123,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 84,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.UNTOUCHABLE"
              }
            ],
            "current_gold": 121,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 120,
            "current_hp": 68,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BEGONE"
            ]
          },
          {
            "current_gold": 123,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 84,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ZAP"
            ]
          },
          {
            "current_gold": 121,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PIERCING_WAIL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 131,
            "current_hp": 64,
            "damage_taken": 4,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.ITERATION"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ITERATION"
              }
            ],
            "current_gold": 137,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 85,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              }
            ],
            "current_gold": 135,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 131,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SPOILS_OF_BATTLE"
            ]
          },
          {
            "current_gold": 137,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BEAM_CELL"
            ]
          },
          {
            "current_gold": 135,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ADRENALINE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 162,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 171,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 170,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 162,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.GLOW"
            ]
          },
          {
            "current_gold": 171,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DUALCAST"
            ]
          },
          {
            "current_gold": 170,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.NEUTRALIZE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.GATHER_LIGHT"
              }
            ],
            "current_gold": 177,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.SKIM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SKIM"
              }
            ],
            "current_gold": 186,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 86,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.ANTICIPATE"
              }
            ],
            "current_gold": 182,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_NORMAL",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWORD_SAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 12,
                "id": "CARD.KINGLY_KICK"
              }
            ],
            "current_gold": 187,
            "current_hp": 37,
            "damage_taken": 27,
            "event_choices": [
              {
                "title": {
                  "key": "PUNCH_OFF.pages.INITIAL.options.I_CAN_TAKE_THEM.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "PUNCH_OFF.pages.I_CAN_TAKE_THEM.options.FIGHT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ENERGY_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.FENCING_MANUAL",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.TURBO"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FERAL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NULL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TURBO"
              }
            ],
            "current_gold": 193,
            "current_hp": 16,
            "damage_taken": 24,
            "event_choices": [
              {
                "title": {
                  "key": "PUNCH_OFF.pages.INITIAL.options.I_CAN_TAKE_THEM.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "PUNCH_OFF.pages.I_CAN_TAKE_THEM.options.FIGHT.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 87,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.DROPLET_OF_PRECOGNITION",
                "was_picked": true
              },
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.RADIANT_TINCTURE",
              "POTION.FIRE_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ORICHALCUM",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLUR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 12,
                "id": "CARD.PREPARED"
              }
            ],
            "current_gold": 194,
            "current_hp": 65,
            "damage_taken": 1,
            "event_choices": [
              {
                "title": {
                  "key": "PUNCH_OFF.pages.INITIAL.options.I_CAN_TAKE_THEM.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "PUNCH_OFF.pages.I_CAN_TAKE_THEM.options.FIGHT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.ENTROPIC_BREW",
                "was_picked": true
              },
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": false
              }
            ],
            "potion_discarded": [
              "POTION.FLEX_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LETTER_OPENER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PUNCH_OFF",
            "room_type": "event",
            "turns_taken": 0
          },
          {
            "model_id": "ENCOUNTER.PUNCH_OFF_EVENT_ENCOUNTER",
            "monster_ids": [
              "MONSTER.PUNCH_CONSTRUCT",
              "MONSTER.PUNCH_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.STARDUST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLOW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.STARDUST"
              }
            ],
            "current_gold": 202,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.BOOT_SEQUENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BOOT_SEQUENCE"
              }
            ],
            "current_gold": 208,
            "current_hp": 13,
            "damage_taken": 4,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 88,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.HIDDEN_DAGGERS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.HIDDEN_DAGGERS"
              }
            ],
            "current_gold": 207,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FOSSIL_STALKER_NORMAL",
            "monster_ids": [
              "MONSTER.FOSSIL_STALKER"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.GATHER_LIGHT"
              }
            ],
            "current_gold": 217,
            "current_hp": 35,
            "damage_taken": 2,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.SCRAPE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BULK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SCRAPE"
              }
            ],
            "current_gold": 216,
            "current_hp": 13,
            "damage_taken": 1,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 89,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.REFLEX"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.REFLEX"
              }
            ],
            "current_gold": 222,
            "current_hp": 64,
            "damage_taken": 1,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.POISON_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.ATTACK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LIVING_FOG_NORMAL",
            "monster_ids": [
              "MONSTER.LIVING_FOG"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 217,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.STARDUST"
            ]
          },
          {
            "current_gold": 216,
            "current_hp": 13,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 89,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.TURBO"
            ]
          },
          {
            "current_gold": 222,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.HIDDEN_DAGGERS"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DYING_STAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.I_AM_INVINCIBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SEVEN_STARS"
                },
                "was_picked": false
              }
            ],
            "current_gold": 292,
            "current_hp": 1,
            "damage_taken": 35,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.VOLTAIC"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ALL_FOR_ONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CONSUMING_SHADOW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.VOLTAIC"
              }
            ],
            "current_gold": 291,
            "current_hp": 2,
            "damage_taken": 13,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 90,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_used": [
              "POTION.HEART_OF_IRON"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.MASTER_PLANNER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.AFTERIMAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SERPENT_FORM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.MASTER_PLANNER"
              }
            ],
            "current_gold": 297,
            "current_hp": 41,
            "damage_taken": 23,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_used": [
              "POTION.POISON_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.WATERFALL_GIANT_BOSS",
            "monster_ids": [
              "MONSTER.WATERFALL_GIANT"
            ],
            "room_type": "boss",
            "turns_taken": 11
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "STORYBOOK",
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOY_BOX",
                "title": {
                  "key": "TOY_BOX.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BRIGHTEST_FLAME"
              }
            ],
            "current_gold": 292,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 59,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.STORYBOOK",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "VERY_HOT_COCOA",
                "title": {
                  "key": "VERY_HOT_COCOA.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TOASTY_MITTENS",
                "title": {
                  "key": "TOASTY_MITTENS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_COMPASS",
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 291,
            "current_hp": 72,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "VERY_HOT_COCOA.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 70,
            "max_hp": 90,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.VERY_HOT_COCOA",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "VERY_HOT_COCOA",
                "title": {
                  "key": "VERY_HOT_COCOA.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "BIIIG_HUG",
                "title": {
                  "key": "BIIIG_HUG.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PUMPKIN_CANDLE",
                "title": {
                  "key": "PUMPKIN_CANDLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 297,
            "current_hp": 64,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "VERY_HOT_COCOA.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 23,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.VERY_HOT_COCOA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.STARDUST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 18,
                  "id": "CARD.ORBIT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SUPERMASSIVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.STARDUST"
              },
              {
                "floor_added_to_deck": 18,
                "id": "CARD.ORBIT"
              }
            ],
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 13,
                "id": "CARD.STARDUST"
              }
            ],
            "current_gold": 305,
            "current_hp": 59,
            "damage_taken": 1,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SCAVENGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CAPACITOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.ENERGY_SURGE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.ENERGY_SURGE"
              }
            ],
            "current_gold": 304,
            "current_hp": 63,
            "damage_taken": 10,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 91,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 18,
                  "id": "CARD.HIDDEN_DAGGERS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 18,
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 18,
                "id": "CARD.HIDDEN_DAGGERS"
              },
              {
                "floor_added_to_deck": 18,
                "id": "CARD.ANTICIPATE"
              }
            ],
            "cards_removed": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 13,
                "id": "CARD.HIDDEN_DAGGERS"
              }
            ],
            "current_gold": 305,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.GLOW"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 19,
                "id": "CARD.GLOW"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 206,
            "current_hp": 59,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 24,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "bought_relics": [
              "RELIC.BREAD"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FTL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SYNCHRONIZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PRODUCTION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HIDDEN_GEM"
                },
                "was_picked": false
              }
            ],
            "current_gold": 84,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 220,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.BOTTLED_POTENTIAL",
                "was_picked": false
              },
              {
                "choice": "POTION.FOCUS_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BREAD",
                "was_picked": true
              },
              {
                "choice": "RELIC.PANTOGRAPH",
                "was_picked": false
              },
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": false
              }
            ]
          },
          {
            "current_gold": 65,
            "current_hp": 64,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 240,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.BREAD",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.LANTERN_KEY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLACK_HOLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.LANTERN_KEY"
              },
              {
                "floor_added_to_deck": 20,
                "id": "CARD.COSMIC_INDIFFERENCE"
              }
            ],
            "current_gold": 218,
            "current_hp": 45,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.INITIAL.options.KEEP_THE_KEY.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.KEEP_THE_KEY.options.FIGHT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FUSION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SUBROUTINE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HELIX_DRILL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LANTERN_KEY"
              }
            ],
            "current_gold": 96,
            "current_hp": 54,
            "damage_taken": 10,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.INITIAL.options.KEEP_THE_KEY.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.KEEP_THE_KEY.options.FIGHT.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 92,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.FYSH_OIL",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.WEAK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.LANTERN_KEY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.LANTERN_KEY"
              }
            ],
            "current_gold": 74,
            "current_hp": 56,
            "damage_taken": 8,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.INITIAL.options.KEEP_THE_KEY.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "THE_LANTERN_KEY.pages.KEEP_THE_KEY.options.FIGHT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_used": [
              "POTION.SKILL_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LANTERN_KEY",
            "room_type": "event",
            "turns_taken": 0
          },
          {
            "model_id": "ENCOUNTER.MYSTERIOUS_KNIGHT_EVENT_ENCOUNTER",
            "monster_ids": [
              "MONSTER.MYSTERIOUS_KNIGHT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 21,
                "id": "CARD.HIDDEN_CACHE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 93,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 25,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SUNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BARRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HUDDLE_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SECRET_TECHNIQUE"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 21,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 92,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_CAPACITY",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": false
              },
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": false
              },
              {
                "choice": "RELIC.MINIATURE_TENT",
                "was_picked": false
              }
            ]
          },
          {
            "current_gold": 74,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 93,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ORBIT"
            ]
          },
          {
            "current_gold": 21,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 92,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.VOLTAIC"
            ]
          },
          {
            "current_gold": 74,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ACROBATICS"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.QUASAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": false
              }
            ],
            "current_gold": 107,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.FYSH_OIL",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 23,
                  "id": "CARD.LEAP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DOUBLE_ENERGY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.LEAP"
              }
            ],
            "current_gold": 33,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 93,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 23,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 23,
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 85,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.POWDERED_DEMISE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 144,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 37,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.LUCKY_FYSH",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 66,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 93,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.PETRIFIED_TOAD",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 116,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.LASTING_CANDY",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 144,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.BRIGHTEST_FLAME"
            ]
          },
          {
            "current_gold": 66,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 93,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SKIM"
            ]
          },
          {
            "current_gold": 116,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.REFLEX"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 19,
            "current_hp": 45,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 125,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SCRAPE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OVERCLOCK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FISTICUFFS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REND"
                },
                "was_picked": false
              }
            ],
            "current_gold": 66,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 93,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RIPPLE_BASIN",
                "was_picked": false
              },
              {
                "choice": "RELIC.GOLD_PLATED_CABLES",
                "was_picked": false
              },
              {
                "choice": "RELIC.RUNIC_CAPACITOR",
                "was_picked": false
              }
            ]
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 41,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 78,
            "current_hp": 39,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 59,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "current_gold": 112,
            "current_hp": 49,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "笨拙"
                  }
                }
              }
            ],
            "gold_gained": 46,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 93,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123
          },
          {
            "current_gold": 103,
            "current_hp": 50,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 62,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.CHARGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MAKE_IT_SO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 28,
                "id": "CARD.CHARGE"
              }
            ],
            "current_gold": 120,
            "current_hp": 30,
            "damage_taken": 9,
            "gold_gained": 42,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 2,
            "player_id": 76561199169575477,
            "potion_used": [
              "POTION.LIQUID_MEMORIES"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STONE_CRACKER",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 28,
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLAW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.BALL_LIGHTNING"
              }
            ],
            "current_gold": 141,
            "current_hp": 48,
            "damage_taken": 2,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 94,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.LUCKY_TONIC",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FYSH_OIL"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ICE_CREAM",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.NIGHTMARE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 28,
                "id": "CARD.NIGHTMARE"
              }
            ],
            "current_gold": 133,
            "current_hp": 33,
            "damage_taken": 17,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POWDERED_DEMISE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BELLOWS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FURNACE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 128,
            "current_hp": 24,
            "damage_taken": 6,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 2,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 29,
                  "id": "CARD.HOTFIX"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TURBO"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.HOTFIX"
              }
            ],
            "current_gold": 152,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 95,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_used": [
              "POTION.LUCKY_TONIC",
              "POTION.DROPLET_OF_PRECOGNITION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 29,
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 29,
                "id": "CARD.ACROBATICS"
              }
            ],
            "current_gold": 142,
            "current_hp": 27,
            "damage_taken": 6,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUMBERING_BEETLE_NORMAL",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_SILK",
              "MONSTER.SLUMBERING_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 128,
            "current_hp": 24,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.GLOW"
            ]
          },
          {
            "current_gold": 152,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 95,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ITERATION"
            ]
          },
          {
            "current_gold": 142,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.VOID_FORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HAMMER_TIME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWORD_SAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.VOID_FORM"
              }
            ],
            "current_gold": 218,
            "current_hp": 6,
            "damage_taken": 18,
            "gold_gained": 90,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 3,
            "player_id": 76561199169575477,
            "potion_used": [
              "POTION.ENERGY_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.IGNITION"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CONSUMING_SHADOW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SIGNAL_BOOST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.IGNITION"
              }
            ],
            "current_gold": 227,
            "current_hp": 14,
            "damage_taken": 36,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 96,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.TRACKING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ACCELERANT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NIGHTMARE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.TRACKING"
              }
            ],
            "current_gold": 217,
            "current_hp": 23,
            "damage_taken": 25,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KAISER_CRAB_BOSS",
            "monster_ids": [
              "MONSTER.CRUSHER",
              "MONSTER.ROCKET"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "FUR_COAT",
                "title": {
                  "key": "FUR_COAT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "DELICATE_FROND",
                "title": {
                  "key": "DELICATE_FROND.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "BRILLIANT_SCARF",
                "title": {
                  "key": "BRILLIANT_SCARF.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 218,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BRILLIANT_SCARF.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 47,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.BRILLIANT_SCARF",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "LOOMING_FRUIT",
                "title": {
                  "key": "LOOMING_FRUIT.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "FUR_COAT",
                "title": {
                  "key": "FUR_COAT.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GLITTER",
                "title": {
                  "key": "GLITTER.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 227,
            "current_hp": 110,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOOMING_FRUIT.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 96,
            "max_hp": 127,
            "max_hp_gained": 31,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.LOOMING_FRUIT",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "BEAUTIFUL_BRACELET",
                "title": {
                  "key": "BEAUTIFUL_BRACELET.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SIGNET_RING",
                "title": {
                  "key": "SIGNET_RING.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "FUR_COAT",
                "title": {
                  "key": "FUR_COAT.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 3,
                    "id": "ENCHANTMENT.SWIFT"
                  },
                  "floor_added_to_deck": 1,
                  "id": "CARD.ADRENALINE"
                },
                "enchantment": "ENCHANTMENT.SWIFT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 3,
                    "id": "ENCHANTMENT.SWIFT"
                  },
                  "floor_added_to_deck": 11,
                  "id": "CARD.ANTICIPATE"
                },
                "enchantment": "ENCHANTMENT.SWIFT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 3,
                    "id": "ENCHANTMENT.SWIFT"
                  },
                  "floor_added_to_deck": 18,
                  "id": "CARD.ANTICIPATE"
                },
                "enchantment": "ENCHANTMENT.SWIFT"
              }
            ],
            "current_gold": 217,
            "current_hp": 60,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BEAUTIFUL_BRACELET.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 37,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.BEAUTIFUL_BRACELET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NONUPEIPE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULWARK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 230,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.EXPLOSIVE_AMPOULE"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SUNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SHADOW_SHIELD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 242,
            "current_hp": 111,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 128,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_SHAPED_ROCK",
              "POTION.POTION_SHAPED_ROCK"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PHANTOM_BLADES"
                },
                "was_picked": false
              }
            ],
            "current_gold": 224,
            "current_hp": 57,
            "damage_taken": 3,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.LANTERN_KEY"
              }
            ],
            "completed_quests": [
              "CARD.LANTERN_KEY"
            ],
            "current_gold": 230,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WAR_HISTORIAN_REPY.pages.INITIAL.options.UNLOCK_CAGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.HISTORY_COURSE",
                "was_picked": true
              }
            ]
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.LANTERN_KEY"
              }
            ],
            "completed_quests": [
              "CARD.LANTERN_KEY"
            ],
            "current_gold": 242,
            "current_hp": 111,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WAR_HISTORIAN_REPY.pages.INITIAL.options.UNLOCK_CAGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 128,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.HISTORY_COURSE",
                "was_picked": true
              }
            ]
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.LANTERN_KEY"
              }
            ],
            "completed_quests": [
              "CARD.LANTERN_KEY"
            ],
            "current_gold": 224,
            "current_hp": 57,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WAR_HISTORIAN_REPY.pages.INITIAL.options.UNLOCK_CAGE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.HISTORY_COURSE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WAR_HISTORIAN_REPY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 230,
            "current_hp": 53,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BATTLEWORN_DUMMY.pages.INITIAL.options.SETTING_2.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 2,
            "player_id": 76561199169575477,
            "upgraded_cards": [
              "CARD.GATHER_LIGHT",
              "CARD.DEFEND_REGENT"
            ]
          },
          {
            "current_gold": 242,
            "current_hp": 112,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BATTLEWORN_DUMMY.pages.INITIAL.options.SETTING_2.title",
                  "table": "events"
                },
                "variables": {
                  "Setting1Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 270.0,
                    "bool_value": false,
                    "string_value": null
                  },
                  "Setting2Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 540.0,
                    "bool_value": false,
                    "string_value": null
                  },
                  "Setting3Hp": {
                    "type": "BaseDynamic",
                    "decimal_value": 1080.0,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 129,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.STRIKE_DEFECT",
              "CARD.ENERGY_SURGE"
            ]
          },
          {
            "current_gold": 224,
            "current_hp": 57,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BATTLEWORN_DUMMY.pages.INITIAL.options.SETTING_2.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "upgraded_cards": [
              "CARD.TRACKING",
              "CARD.STRIKE_SILENT"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BATTLEWORN_DUMMY",
            "room_type": "event",
            "turns_taken": 0
          },
          {
            "model_id": "ENCOUNTER.BATTLEWORN_DUMMY_EVENT_ENCOUNTER",
            "monster_ids": [
              "MONSTER.BATTLE_FRIEND_V2"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 80,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 150,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DOUBLE_ENERGY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BULK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TAG_TEAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAND_OF_GREED"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 142,
            "current_hp": 112,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 129,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.ART_OF_WAR",
                "was_picked": false
              },
              {
                "choice": "RELIC.GIRYA",
                "was_picked": false
              },
              {
                "choice": "RELIC.ORRERY",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 36,
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 36,
                "id": "CARD.FOOTWORK"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 85,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 39,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SUMMON_FORTH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 95,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 37,
                  "id": "CARD.TEMPEST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.TEMPEST"
              }
            ],
            "current_gold": 155,
            "current_hp": 113,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 130,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.POTION_SHAPED_ROCK",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 37,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOUNCING_FLASK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 37,
                "id": "CARD.PREPARED"
              }
            ],
            "current_gold": 97,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 127,
            "current_hp": 53,
            "damage_taken": 0,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.CANDELABRA",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 191,
            "current_hp": 113,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 130,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 136,
            "current_hp": 57,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.SHURIKEN",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 127,
            "current_hp": 38,
            "damage_taken": 15,
            "event_choices": [
              {
                "title": {
                  "key": "HUNGRY_FOR_MUSHROOMS.pages.INITIAL.options.FRAGRANT_MUSHROOM.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.FRAGRANT_MUSHROOM",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.DEFEND_REGENT",
              "CARD.FOREGONE_CONCLUSION",
              "CARD.CHARGE"
            ]
          },
          {
            "current_gold": 191,
            "current_hp": 98,
            "damage_taken": 15,
            "event_choices": [
              {
                "title": {
                  "key": "HUNGRY_FOR_MUSHROOMS.pages.INITIAL.options.FRAGRANT_MUSHROOM.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 130,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.FRAGRANT_MUSHROOM",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.FIGHT_THROUGH",
              "CARD.BOOT_SEQUENCE",
              "CARD.DEFEND_DEFECT"
            ]
          },
          {
            "current_gold": 136,
            "current_hp": 42,
            "damage_taken": 15,
            "event_choices": [
              {
                "title": {
                  "key": "HUNGRY_FOR_MUSHROOMS.pages.INITIAL.options.FRAGRANT_MUSHROOM.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.FRAGRANT_MUSHROOM",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.PREPARED",
              "CARD.ANTICIPATE",
              "CARD.SURVIVOR"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.HUNGRY_FOR_MUSHROOMS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 154,
            "current_hp": 17,
            "damage_taken": 28,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 69,
            "max_hp_gained": 7,
            "max_hp_lost": 1,
            "player_id": 76561199169575477,
            "relic_choices": [
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 40,
                  "id": "CARD.SKIM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ICE_LANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SKIM"
              }
            ],
            "current_gold": 218,
            "current_hp": 89,
            "damage_taken": 10,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 131,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_SHAPED_ROCK"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STONE_CRACKER",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BOUNCING_FLASK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              }
            ],
            "current_gold": 169,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.WHETSTONE",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.DAGGER_THROW",
              "CARD.STRIKE_SILENT"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
            "monster_ids": [
              "MONSTER.MECHA_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 154,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 218,
            "current_hp": 89,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 131,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SKIM"
            ]
          },
          {
            "current_gold": 169,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.FOOTWORK"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "current_gold": 154,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477
          },
          {
            "bought_potions": [
              "POTION.POWER_POTION"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.REFRACT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHAOS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SMOKESTACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SHOCKWAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MIMIC"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 42,
            "current_hp": 89,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 176,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 131,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "potion_discarded": [
              "POTION.EXPLOSIVE_AMPOULE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAMBRACE",
                "was_picked": false
              },
              {
                "choice": "RELIC.REPTILE_TRINKET",
                "was_picked": false
              },
              {
                "choice": "RELIC.LAVA_LAMP",
                "was_picked": false
              }
            ]
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 44,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 125,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CLOAK_OF_STARS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              }
            ],
            "current_gold": 184,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.STABLE_SERUM"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BOOT_SEQUENCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFRACT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NULL"
                },
                "was_picked": false
              }
            ],
            "current_gold": 71,
            "current_hp": 90,
            "damage_taken": 0,
            "gold_gained": 29,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 132,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "relic_choices": [
              {
                "choice": "RELIC.BELLOWS",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SHADOWMELD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": false
              }
            ],
            "current_gold": 71,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNIGHTS_ELITE",
            "monster_ids": [
              "MONSTER.FLAIL_KNIGHT",
              "MONSTER.SPECTRAL_KNIGHT",
              "MONSTER.MAGI_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 184,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199169575477,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.VOID_FORM"
            ]
          },
          {
            "current_gold": 71,
            "current_hp": 129,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 39,
            "max_hp": 132,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 71,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 184,
            "current_hp": 31,
            "damage_taken": 6,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 67,
            "max_hp_gained": 0,
            "max_hp_lost": 2,
            "player_id": 76561199169575477,
            "potion_used": [
              "POTION.SWIFT_POTION"
            ]
          },
          {
            "current_gold": 71,
            "current_hp": 113,
            "damage_taken": 17,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 133,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561199466895123,
            "potion_used": [
              "POTION.POWER_POTION"
            ]
          },
          {
            "current_gold": 71,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198237752388,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": true
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.TOUCH_OF_INSANITY",
              "POTION.ENTROPIC_BREW",
              "POTION.HEART_OF_IRON",
              "POTION.ATTACK_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DOORMAKER_BOSS",
            "monster_ids": [
              "MONSTER.DOOR"
            ],
            "room_type": "boss",
            "turns_taken": 5
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.FOREGONE_CONCLUSION"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.BEGONE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.GLOW"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.SPOILS_OF_BATTLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.GATHER_LIGHT"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.KINGLY_KICK"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.GATHER_LIGHT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.BRIGHTEST_FLAME"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.STARDUST"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.ORBIT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.GLOW"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.COSMIC_INDIFFERENCE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.HIDDEN_CACHE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.CHARGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.VOID_FORM"
        }
      ],
      "id": 76561199169575477,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.ENERGY_POTION",
          "slot_index": 1
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.GORGET"
        },
        {
          "floor_added_to_deck": 12,
          "id": "RELIC.FENCING_MANUAL"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.STORYBOOK"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.LUCKY_FYSH"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.STONE_CRACKER"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.BRILLIANT_SCARF"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.HISTORY_COURSE"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.CANDELABRA"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.FRAGRANT_MUSHROOM"
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.STRAWBERRY"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.VAJRA"
        }
      ]
    },
    {
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.FIGHT_THROUGH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.BEAM_CELL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 7,
          "id": "CARD.ITERATION"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.SKIM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 12,
          "id": "CARD.TURBO"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 13,
          "id": "CARD.BOOT_SEQUENCE"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.SCRAPE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.VOLTAIC"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.ENERGY_SURGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.LEAP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.BALL_LIGHTNING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 29,
          "id": "CARD.HOTFIX"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.IGNITION"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 37,
          "id": "CARD.TEMPEST"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 40,
          "id": "CARD.SKIM"
        }
      ],
      "id": 76561199466895123,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.POTION_SHAPED_ROCK",
          "slot_index": 0
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.MASSIVE_SCROLL"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 12,
          "id": "RELIC.ORICHALCUM"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.VERY_HOT_COCOA"
        },
        {
          "floor_added_to_deck": 19,
          "id": "RELIC.BREAD"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.PETRIFIED_TOAD"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.ICE_CREAM"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.LOOMING_FRUIT"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.HISTORY_COURSE"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.ODDLY_SMOOTH_STONE"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.FRAGRANT_MUSHROOM"
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.STONE_CRACKER"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.BELLOWS"
        }
      ]
    },
    {
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 3,
            "id": "ENCHANTMENT.SWIFT"
          },
          "floor_added_to_deck": 1,
          "id": "CARD.ADRENALINE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.DAGGER_THROW"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 3,
          "id": "CARD.ACROBATICS"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.UNTOUCHABLE"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 3,
            "id": "ENCHANTMENT.SWIFT"
          },
          "floor_added_to_deck": 11,
          "id": "CARD.ANTICIPATE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 12,
          "id": "CARD.PREPARED"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 14,
          "id": "CARD.REFLEX"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.MASTER_PLANNER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.HIDDEN_DAGGERS"
        },
        {
          "enchantment": {
            "amount": 3,
            "id": "ENCHANTMENT.SWIFT"
          },
          "floor_added_to_deck": 18,
          "id": "CARD.ANTICIPATE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 28,
          "id": "CARD.NIGHTMARE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 29,
          "id": "CARD.ACROBATICS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.TRACKING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 36,
          "id": "CARD.FOOTWORK"
        },
        {
          "floor_added_to_deck": 37,
          "id": "CARD.PREPARED"
        }
      ],
      "id": 76561198237752388,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 12,
          "id": "RELIC.LETTER_OPENER"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.VERY_HOT_COCOA"
        },
        {
          "floor_added_to_deck": 19,
          "id": "RELIC.BREAD"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.LASTING_CANDY",
          "props": {
            "ints": [
              {
                "name": "CombatsSeen",
                "value": 9
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.BELLOWS"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.BEAUTIFUL_BRACELET"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.HISTORY_COURSE"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.SHURIKEN"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.FRAGRANT_MUSHROOM"
        },
        {
          "floor_added_to_deck": 40,
          "id": "RELIC.WHETSTONE"
        },
        {
          "floor_added_to_deck": 43,
          "id": "RELIC.VAJRA"
        }
      ]
    }
  ],
  "run_time": 3960,
  "schema_version": 8,
  "seed": "UFDEK0NBP6",
  "start_time": 1774055192,
  "was_abandoned": false,
  "win": true
}